#!/usr/bin/env python
"""
Tests for RosBag, RosStream, RosMessage, and SyncRosStreams.

RosBag tests use synthetic fixture files generated by
``tests/create_ros_fixture.py`` and committed to the repository.

RosStream tests inject messages directly into ``_process_frame`` without a
real rosbridge connection, so they run in any environment without ROS.

SyncRosStreams tests drive the synchroniser with synthetic timestamped objects
constructed entirely in Python.
"""

from __future__ import annotations

import threading
import time
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

import numpy as np
import pytest

from machinevisiontoolbox import Image
from machinevisiontoolbox.Sources import (
    RosMessage,
    SyncRosStreams,
    _resolve_typestore,
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

HERE = Path(__file__).parent
ROS1_BAG = HERE / "data" / "test_ros1.bag"
ROS2_BAG = HERE / "data" / "test_ros2"

_rosbags_available = ROS1_BAG.exists() and ROS2_BAG.exists()
_skip_bags = pytest.mark.skipif(
    not _rosbags_available,
    reason="ROS bag fixtures missing – run tests/create_ros_fixture.py first",
)

try:
    from machinevisiontoolbox.Sources import RosBag

    _rosbags_importable = True
except ImportError:
    _rosbags_importable = False

_skip_import = pytest.mark.skipif(
    not _rosbags_importable, reason="rosbags package not installed"
)

try:
    from machinevisiontoolbox.Sources import RosStream

    _roslibpy_importable = True
except ImportError:
    _roslibpy_importable = False

_skip_roslibpy = pytest.mark.skipif(
    not _roslibpy_importable, reason="roslibpy package not installed"
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

N_FRAMES = 3           # messages per topic in the fixture bags
STAMP0 = 1_700_000_000_000_000_000  # first timestamp (ns)
STEP = 100_000_000                  # timestamp step between frames (ns)
W, H = 8, 6            # image dimensions in fixture


# ---------------------------------------------------------------------------
# _resolve_typestore
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not _rosbags_importable, reason="rosbags not installed")
class TestResolveTypestore(unittest.TestCase):
    def test_exact_match(self):
        ts = _resolve_typestore("ROS1_NOETIC")
        self.assertIsNotNone(ts)

    def test_case_insensitive(self):
        ts1 = _resolve_typestore("ROS1_NOETIC")
        ts2 = _resolve_typestore("ros1_noetic")
        # both should return a typestore without raising
        self.assertIsNotNone(ts2)

    def test_short_name(self):
        ts = _resolve_typestore("noetic")
        self.assertIsNotNone(ts)

    def test_ros2_short_name(self):
        ts = _resolve_typestore("humble")
        self.assertIsNotNone(ts)

    def test_unknown_raises(self):
        with self.assertRaises(ValueError):
            _resolve_typestore("nonexistent_distro")

    def test_ambiguous_raises(self):
        # "ros" matches both ROS1_* and ROS2_* entries
        with self.assertRaises(ValueError):
            _resolve_typestore("ros")


# ---------------------------------------------------------------------------
# RosBag – ROS 1
# ---------------------------------------------------------------------------

@_skip_import
@_skip_bags
class TestRosBagRos1(unittest.TestCase):

    def _bag(self, **kwargs):
        return RosBag(str(ROS1_BAG), release="noetic", **kwargs)

    # --- topics() ---

    def test_topics_returns_all_three(self):
        topics = self._bag(msgfilter=None).topics()
        self.assertIn("/camera/compressed", topics)
        self.assertIn("/camera/raw", topics)
        self.assertIn("/imu/data", topics)

    def test_topics_msgtype(self):
        topics = self._bag(msgfilter=None).topics()
        self.assertIn("CompressedImage", topics["/camera/compressed"])
        self.assertIn("Image", topics["/camera/raw"])
        self.assertIn("Imu", topics["/imu/data"])

    # --- default iteration (msgfilter="Image") ---

    def test_default_yields_images_only(self):
        msgs = list(self._bag())
        self.assertEqual(len(msgs), N_FRAMES * 2)   # compressed + raw
        for m in msgs:
            self.assertIsInstance(m, Image)

    def test_image_shape(self):
        for img in self._bag():
            self.assertEqual(img.shape, (H, W, 3))

    def test_image_timestamp(self):
        imgs = list(self._bag())
        stamps = [img.timestamp for img in imgs]
        # timestamps monotonically increase by STEP (interleaved topics)
        unique_stamps = sorted(set(stamps))
        self.assertEqual(len(unique_stamps), N_FRAMES)
        for i in range(1, N_FRAMES):
            self.assertEqual(unique_stamps[i] - unique_stamps[i - 1], STEP)

    def test_image_topic_attribute(self):
        for img in self._bag():
            self.assertIn(img.topic, {"/camera/compressed", "/camera/raw"})

    # --- topic filter ---

    def test_topicfilter_compressed_only(self):
        msgs = list(self._bag(topicfilter="/camera/compressed"))
        self.assertEqual(len(msgs), N_FRAMES)
        for m in msgs:
            self.assertEqual(m.topic, "/camera/compressed")

    def test_topicfilter_raw_only(self):
        msgs = list(self._bag(topicfilter="/camera/raw"))
        self.assertEqual(len(msgs), N_FRAMES)
        for m in msgs:
            self.assertEqual(m.topic, "/camera/raw")

    def test_topicfilter_list(self):
        msgs = list(
            self._bag(topicfilter=["/camera/compressed", "/camera/raw"])
        )
        self.assertEqual(len(msgs), N_FRAMES * 2)

    # --- message type filter ---

    def test_msgfilter_none_yields_all(self):
        msgs = list(self._bag(msgfilter=None))
        self.assertEqual(len(msgs), N_FRAMES * 3)

    def test_msgfilter_imu_yields_imu(self):
        msgs = list(self._bag(msgfilter="Imu"))
        self.assertEqual(len(msgs), N_FRAMES)
        for m in msgs:
            self.assertNotIsInstance(m, Image)

    def test_imu_passthrough_has_topic_and_timestamp(self):
        msgs = list(self._bag(msgfilter="Imu"))
        for m in msgs:
            self.assertTrue(hasattr(m, "topic"))
            self.assertTrue(hasattr(m, "timestamp"))
            self.assertEqual(m.topic, "/imu/data")

    # --- context manager ---

    def test_context_manager_closes(self):
        bag = self._bag()
        with bag:
            imgs = list(bag)
        # reader should be closed after exiting context
        self.assertIsNone(bag.reader)

    # --- repr / str ---

    def test_repr(self):
        r = repr(self._bag())
        self.assertIn("RosBag", r)
        self.assertIn("noetic", r.lower())

    # --- format helpers ---

    def test_format_duration(self):
        self.assertEqual(RosBag.format_duration(3661_000_000_000), "01:01:01")
        self.assertEqual(RosBag.format_duration(0), "00:00:00")

    def test_format_local_time_returns_string(self):
        s = RosBag.format_local_time(STAMP0)
        self.assertIsInstance(s, str)
        self.assertIn("2023", s)


# ---------------------------------------------------------------------------
# RosBag – ROS 2  (same logical tests, different fixture path / release)
# ---------------------------------------------------------------------------

@_skip_import
@_skip_bags
class TestRosBagRos2(unittest.TestCase):

    def _bag(self, **kwargs):
        return RosBag(str(ROS2_BAG), release="humble", **kwargs)

    def test_topics_returns_all_three(self):
        topics = self._bag(msgfilter=None).topics()
        self.assertIn("/camera/compressed", topics)
        self.assertIn("/camera/raw", topics)
        self.assertIn("/imu/data", topics)

    def test_default_yields_images_only(self):
        msgs = list(self._bag())
        self.assertEqual(len(msgs), N_FRAMES * 2)
        for m in msgs:
            self.assertIsInstance(m, Image)

    def test_image_shape(self):
        for img in self._bag():
            self.assertEqual(img.shape, (H, W, 3))

    def test_image_timestamp(self):
        imgs = list(self._bag())
        unique_stamps = sorted({img.timestamp for img in imgs})
        self.assertEqual(len(unique_stamps), N_FRAMES)

    def test_msgfilter_none_yields_all(self):
        msgs = list(self._bag(msgfilter=None))
        self.assertEqual(len(msgs), N_FRAMES * 3)

    def test_imu_passthrough_has_topic_and_timestamp(self):
        for m in self._bag(msgfilter="Imu"):
            self.assertTrue(hasattr(m, "topic"))
            self.assertTrue(hasattr(m, "timestamp"))


# ---------------------------------------------------------------------------
# RosMessage dataclass
# ---------------------------------------------------------------------------

class TestRosMessage(unittest.TestCase):

    def _make(self, **kwargs):
        defaults = dict(
            topic="/test", msgtype="std_msgs/msg/String", timestamp=42, data={"data": "hi"}
        )
        defaults.update(kwargs)
        return RosMessage(**defaults)

    def test_fields_accessible(self):
        m = self._make()
        self.assertEqual(m.topic, "/test")
        self.assertEqual(m.msgtype, "std_msgs/msg/String")
        self.assertEqual(m.timestamp, 42)
        self.assertEqual(m.data, {"data": "hi"})

    def test_frozen(self):
        m = self._make()
        with self.assertRaises(Exception):
            m.timestamp = 99  # frozen dataclass


# ---------------------------------------------------------------------------
# RosStream – injected callback tests (no ROS runtime needed)
# ---------------------------------------------------------------------------

def _make_mock_stream(output="image", message="sensor_msgs/CompressedImage"):
    """Build a RosStream-like object bypassing roslibpy entirely."""
    try:
        import roslibpy
    except ImportError:
        pytest.skip("roslibpy not installed")

    with (
        patch("machinevisiontoolbox.Sources.roslibpy.Ros") as MockRos,
        patch("machinevisiontoolbox.Sources.roslibpy.Topic") as MockTopic,
    ):
        MockRos.return_value.run = MagicMock()
        MockTopic.return_value.subscribe = MagicMock()
        stream = RosStream("/test", message=message, output=output)
    stream.client = MagicMock()
    stream._topic = MagicMock()
    return stream


@pytest.mark.skipif(not _roslibpy_importable, reason="roslibpy not installed")
class TestRosStreamCallback(unittest.TestCase):

    def _jpeg_msg(self, r=128, g=100, b=50):
        """Build a minimal roslibpy compressed-image message dict."""
        import base64
        import io
        from PIL import Image as PILImg

        arr = np.full((4, 4, 3), [r, g, b], dtype=np.uint8)
        buf = io.BytesIO()
        PILImg.fromarray(arr, "RGB").save(buf, format="JPEG", quality=95)
        return {
            "header": {"stamp": {"secs": 10, "nsecs": 500_000_000}},
            "format": "jpeg",
            "data": base64.b64encode(buf.getvalue()).decode(),
        }

    def test_image_mode_sets_frame(self):
        stream = _make_mock_stream(output="image")
        stream._process_frame(self._jpeg_msg())
        self.assertIsNotNone(stream._latest_frame)
        self.assertIsNone(stream._latest_message)

    def test_image_mode_timestamp(self):
        stream = _make_mock_stream(output="image")
        stream._process_frame(self._jpeg_msg())
        # secs=10, nsecs=500_000_000 → 10_500_000_000 ns
        self.assertEqual(stream._latest_timestamp, 10_500_000_000)

    def test_message_mode_sets_rosmessage(self):
        stream = _make_mock_stream(
            output="message", message="sensor_msgs/Imu"
        )
        msg = {"header": {"stamp": {"secs": 5, "nsecs": 0}}, "data": "x"}
        stream._process_frame(msg)
        self.assertIsNone(stream._latest_frame)
        self.assertIsInstance(stream._latest_message, RosMessage)

    def test_message_mode_rosmessage_fields(self):
        stream = _make_mock_stream(
            output="message", message="sensor_msgs/Imu"
        )
        payload = {"header": {"stamp": {"secs": 7, "nsecs": 0}}, "val": 3}
        stream._process_frame(payload)
        m = stream._latest_message
        self.assertEqual(m.topic, "/test")
        self.assertEqual(m.msgtype, "sensor_msgs/Imu")
        self.assertEqual(m.timestamp, 7_000_000_000)
        self.assertEqual(m.data, payload)

    def test_zero_stamp_fallback(self):
        stream = _make_mock_stream(output="image")
        before = time.time_ns()
        stream._process_frame(self._jpeg_msg(r=0))
        # Force zero stamp
        msg = {
            "header": {"stamp": {"secs": 0, "nsecs": 0}},
            "format": "jpeg",
            "data": self._jpeg_msg(r=0)["data"],
        }
        stream._process_frame(msg)
        after = time.time_ns()
        self.assertGreaterEqual(stream._latest_timestamp, before)
        self.assertLessEqual(stream._latest_timestamp, after)

    def test_ros2_stamp_field_names(self):
        """Accept ROS2-style 'sec'/'nanosec' stamp fields."""
        stream = _make_mock_stream(output="image")
        import base64
        import io
        from PIL import Image as PILImg

        arr = np.zeros((4, 4, 3), dtype=np.uint8)
        buf = io.BytesIO()
        PILImg.fromarray(arr, "RGB").save(buf, format="JPEG", quality=95)
        msg = {
            "header": {"stamp": {"sec": 3, "nanosec": 200_000_000}},
            "format": "jpeg",
            "data": base64.b64encode(buf.getvalue()).decode(),
        }
        stream._process_frame(msg)
        self.assertEqual(stream._latest_timestamp, 3_200_000_000)

    def test_event_set_after_callback(self):
        stream = _make_mock_stream(output="image")
        self.assertFalse(stream._frame_event.is_set())
        stream._process_frame(self._jpeg_msg())
        self.assertTrue(stream._frame_event.is_set())


@pytest.mark.skipif(not _roslibpy_importable, reason="roslibpy not installed")
class TestRosStreamValidation(unittest.TestCase):

    def test_invalid_output_value(self):
        with self.assertRaises(ValueError):
            _make_mock_stream(output="bad_value")

    def test_image_output_requires_image_msgtype(self):
        with self.assertRaises(ValueError):
            _make_mock_stream(output="image", message="sensor_msgs/Imu")

    def test_publish_only_iter_raises(self):
        with (
            patch("machinevisiontoolbox.Sources.roslibpy.Ros") as MockRos,
            patch("machinevisiontoolbox.Sources.roslibpy.Topic"),
        ):
            MockRos.return_value.run = MagicMock()
            stream = RosStream("/pub", subscribe=False)
        stream.client = MagicMock()
        stream._topic = MagicMock()
        with self.assertRaises(TypeError):
            iter(stream)
        with self.assertRaises(TypeError):
            next(stream)


# ---------------------------------------------------------------------------
# SyncRosStreams – pure Python, no ROS needed
# ---------------------------------------------------------------------------

class _FakeItem:
    """Minimal timestamped item for SyncRosStreams tests."""

    def __init__(self, timestamp: int, value: str = ""):
        self.timestamp = timestamp
        self.value = value


def _fake_stream(*timestamps):
    """Iterator yielding _FakeItem objects for the given timestamps."""

    def _gen():
        for t in timestamps:
            yield _FakeItem(t)

    s = MagicMock()
    s._subscribe = True
    s.__enter__ = lambda self: self
    s.__exit__ = MagicMock(return_value=False)
    s.__iter__ = lambda self: _gen()
    return s


class TestSyncRosStreams(unittest.TestCase):

    def test_requires_two_streams(self):
        s = _fake_stream(1)
        with self.assertRaises(ValueError):
            SyncRosStreams([s])

    def test_tolerance_must_be_positive(self):
        s1, s2 = _fake_stream(1), _fake_stream(1)
        with self.assertRaises(ValueError):
            SyncRosStreams([s1, s2], tolerance=0)
        with self.assertRaises(ValueError):
            SyncRosStreams([s1, s2], tolerance=-1)

    def test_publish_only_stream_rejected(self):
        s1 = _fake_stream(1)
        s2 = _fake_stream(1)
        s2._subscribe = False
        with self.assertRaises(ValueError):
            SyncRosStreams([s1, s2])

    def test_exact_match(self):
        t = 1_000_000_000
        s1 = _fake_stream(t)
        s2 = _fake_stream(t)
        sync = SyncRosStreams([s1, s2], tolerance=0.02)
        result = list(sync)
        self.assertEqual(len(result), 1)
        a, b = result[0]
        self.assertEqual(a.timestamp, t)
        self.assertEqual(b.timestamp, t)

    def test_within_tolerance_matches(self):
        tol = 20_000_000   # 20 ms in ns
        t0 = 1_000_000_000
        # stream2 is 10 ms ahead — within 20 ms tolerance
        s1 = _fake_stream(t0)
        s2 = _fake_stream(t0 + 10_000_000)
        sync = SyncRosStreams([s1, s2], tolerance=0.02)
        result = list(sync)
        self.assertEqual(len(result), 1)

    def test_outside_tolerance_drops_oldest(self):
        t0 = 1_000_000_000
        # stream1: t0, t0+50ms; stream2: t0+40ms
        # t0 vs t0+40ms → 40 ms apart > 10 ms tol → drop t0 from s1
        # t0+50ms vs t0+40ms → 10 ms apart ≤ 10 ms tol → match
        s1 = _fake_stream(t0, t0 + 50_000_000)
        s2 = _fake_stream(t0 + 40_000_000)
        sync = SyncRosStreams([s1, s2], tolerance=0.01)
        result = list(sync)
        self.assertEqual(len(result), 1)
        a, b = result[0]
        self.assertEqual(a.timestamp, t0 + 50_000_000)
        self.assertEqual(b.timestamp, t0 + 40_000_000)

    def test_multiple_pairs(self):
        base = 1_000_000_000
        step = 100_000_000
        ts1 = [base + i * step for i in range(3)]
        ts2 = [base + i * step + 5_000_000 for i in range(3)]  # 5 ms offset
        s1 = _fake_stream(*ts1)
        s2 = _fake_stream(*ts2)
        sync = SyncRosStreams([s1, s2], tolerance=0.02)
        result = list(sync)
        self.assertEqual(len(result), 3)

    def test_timestamp_ns_missing_raises(self):
        class NoTimestamp:
            pass

        with self.assertRaises(TypeError):
            SyncRosStreams._timestamp_ns(NoTimestamp())

    def test_repr(self):
        s1, s2 = _fake_stream(1), _fake_stream(1)
        sync = SyncRosStreams([s1, s2], tolerance=0.05)
        r = repr(sync)
        self.assertIn("SyncRosStreams", r)
        self.assertIn("nstreams=2", r)


if __name__ == "__main__":
    unittest.main()
