"""
Protocol for Image mixin classes.

Every ``Image*Mixin`` inherits from ``_ImageBase`` at type-check time only,
giving static-analysis tools (Pylance, mypy) a single authoritative declaration
of the attributes and methods that are provided by the concrete ``Image`` class
at composition time.  This removes the need for duplicated ``if TYPE_CHECKING:``
attribute stubs inside every mixin.

At runtime the mixins inherit from plain ``object`` — the Protocol is never
instantiated and adds nothing to the MRO.
"""

from __future__ import annotations

import sys
from typing import Any, Protocol

if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self
import numpy as np

from machinevisiontoolbox.mvtb_types import Array2d, Array3d, Dtype


class _ImageBase(Protocol):
    """
    Protocol describing the full ``Image`` interface.

    Mixin classes inherit from this *at type-check time only* (via
    ``TYPE_CHECKING`` guards) so that attribute accesses such as ``self._A``,
    ``self.iscolor`` and ``self.to_int()`` resolve correctly without any
    runtime overhead.
    """

    # ---- pixel data --------------------------------------------------
    _A: np.ndarray

    @property
    def A(self) -> np.ndarray: ...

    @property
    def image(self) -> np.ndarray: ...  # deprecated

    @property
    def array(self) -> np.ndarray: ...

    @property
    def rgb(self) -> np.ndarray: ...

    @property
    def bgr(self) -> np.ndarray: ...

    # ---- type flags --------------------------------------------------
    @property
    def iscolor(self) -> bool: ...
    @property
    def isint(self) -> bool: ...
    @property
    def isfloat(self) -> bool: ...
    @property
    def isbool(self) -> bool: ...
    @property
    def isrgb(self) -> bool: ...
    @property
    def isbgr(self) -> bool: ...

    # ---- pixel metadata ----------------------------------------------
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def colororder(self) -> dict[str, int] | None: ...
    @property
    def colororder_str(self) -> str | None: ...
    @property
    def name(self) -> str | None: ...

    # plain instance attributes
    id: int | None
    domain: Any

    # ---- shape / geometry --------------------------------------------
    @property
    def nplanes(self) -> int: ...
    @property
    def shape(self) -> tuple[int, int] | tuple[int, int, int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def umax(self) -> int: ...
    @property
    def vmax(self) -> int: ...
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def npixels(self) -> int: ...
    @property
    def numnan(self) -> int: ...
    @property
    def numinf(self) -> int: ...
    @property
    def centre(self) -> tuple[float, float]: ...
    @property
    def center(self) -> tuple[float, float]: ...
    @property
    def centre_int(self) -> tuple[int, int]: ...
    @property
    def center_int(self) -> tuple[int, int]: ...

    # ---- pixel value constants ---------------------------------------
    @property
    def minval(self) -> int | float: ...
    @property
    def maxval(self) -> int | float: ...
    @property
    def true(self) -> int | float: ...
    @property
    def false(self) -> int | float: ...

    # ---- type / value conversion -------------------------------------
    def to(self, dtype: Dtype) -> Self: ...
    def astype(self, dtype: Dtype) -> Self: ...
    def array_as(self, dtype: Dtype = ...) -> np.ndarray: ...
    def cast(self, value: int | float | np.ndarray) -> Any: ...
    def like(self, value: int | float, maxint: int | None = ...) -> Any: ...
    def copy(self, copy: bool = ...) -> Self: ...
    def to_int(self, intclass: Dtype = ...) -> np.ndarray: ...  # deprecated
    def to_float(self, floatclass: Dtype = ...) -> np.ndarray: ...  # deprecated

    # ---- spatial / plane access --------------------------------------
    def plane(self, planes: Any) -> Self: ...
    def contains(self, p: Array2d) -> bool | np.ndarray: ...
    def meshgrid(self) -> tuple[np.ndarray, np.ndarray]: ...
    def interp2d(self, *args: Any, **kwargs: Any) -> np.ndarray: ...

    # ---- colour ------------------------------------------------------
    def mono(self) -> Self: ...
    def red(self) -> Self: ...
    def green(self) -> Self: ...
    def blue(self) -> Self: ...
    def colorspace(self, dst: str, src: str | None = ...) -> Self: ...
    def invert(self) -> Self: ...

    # ---- border handling (defined in ImageSpatialMixin) --------------
    @staticmethod
    def _bordertype_cv(border: str, exclude: Any = None) -> int: ...
    @staticmethod
    def _bordertype_sp(border: str, exclude: Any = None) -> str: ...
    @staticmethod
    def _opencv_type_check(array: np.ndarray, *accepted_types: str) -> None: ...

    # ---- other image methods -----------------------------------------
    def smooth(self, *args: Any, **kwargs: Any) -> Self: ...
    def convolve(self, *args: Any, **kwargs: Any) -> Self: ...
    def trim(self, *args: Any, **kwargs: Any) -> Self: ...
    def colorize(self, *args: Any, **kwargs: Any) -> Self: ...
    def moments(self, binary: bool = ...) -> dict[str, float]: ...
    def disp(self, *args: Any, **kwargs: Any) -> Any: ...
    def paste(self, *args: Any, **kwargs: Any) -> None: ...

    @classmethod
    def Constant(cls, *args: Any, **kwargs: Any) -> Self: ...

    # ---- whole-image statistics -------------------------------------
    @property
    def min(self) -> int | float: ...
    @property
    def max(self) -> int | float: ...
    @property
    def sum(self) -> int | float: ...
    @property
    def mean(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def var(self) -> float: ...
    @property
    def median(self) -> int | float: ...
    @property
    def stats(self) -> dict[str, Any]: ...
    def __iter__(self) -> Any: ...

    # ---- arithmetic operators ----------------------------------------
    def __add__(self, other: Any) -> Self: ...
    def __radd__(self, other: Any) -> Self: ...
    def __iadd__(self, other: Any) -> Self: ...
    def __sub__(self, other: Any) -> Self: ...
    def __rsub__(self, other: Any) -> Self: ...
    def __isub__(self, other: Any) -> Self: ...
    def __mul__(self, other: Any) -> Self: ...
    def __rmul__(self, other: Any) -> Self: ...
    def __imul__(self, other: Any) -> Self: ...
    def __truediv__(self, other: Any) -> Self: ...
    def __rtruediv__(self, other: Any) -> Self: ...
    def __itruediv__(self, other: Any) -> Self: ...
    def __ifloordiv__(self, other: Any) -> Self: ...
    def __iand__(self, other: Any) -> Self: ...
    def __ior__(self, other: Any) -> Self: ...
    def __ixor__(self, other: Any) -> Self: ...
    def __ilshift__(self, other: Any) -> Self: ...
    def __irshift__(self, other: Any) -> Self: ...
