"""
Stub base class for Image mixin classes.

Every ``Image*Mixin`` inherits from ``_ImageBase``, giving static-analysis
tools (Pylance, mypy) a single authoritative declaration of the attributes and
methods that are provided by the concrete ``Image`` class at composition time.
This removes the need for duplicated ``if TYPE_CHECKING:`` attribute stubs
inside every mixin.

At runtime ``_ImageBase`` is a plain class whose body contains only
annotations (no actual attribute values), so there is zero behavioural impact.
"""

from __future__ import annotations

import sys
from typing import Any

if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self
import numpy as np

from machinevisiontoolbox.mvtb_types import Array2d, Array3d, Dtype


class _ImageBase:
    """
    Stub base class whose annotations describe the full ``Image`` interface.

    Mixin classes inherit from this so that accesses such as ``self.A``,
    ``self.iscolor`` and ``self.to_int()`` are visible to the type checker
    without repeating the declarations in every mixin file.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    # ---- pixel data --------------------------------------------------
    _A: np.ndarray
    A: np.ndarray
    image: np.ndarray  # deprecated
    array: np.ndarray

    # ---- type flags --------------------------------------------------
    iscolor: bool
    isint: bool
    isfloat: bool
    isbool: bool
    isrgb: bool
    isbgr: bool

    # ---- pixel metadata ----------------------------------------------
    dtype: np.dtype
    colororder: dict[str, int] | None
    colororder_str: str | None
    name: str | None
    id: int | None
    domain: Any

    # ---- shape / geometry --------------------------------------------
    nplanes: int
    shape: tuple[int, int] | tuple[int, int, int]
    ndim: int
    width: int
    height: int
    umax: int
    vmax: int
    size: tuple[int, int]
    npixels: int
    numnan: int
    numinf: int

    # ---- pixel value constants ---------------------------------------
    minval: float
    maxval: float
    true: int | float
    false: int | float

    # ---- type / value conversion -------------------------------------
    def to(self, dtype: Dtype) -> Self: ...
    def astype(self, dtype: Dtype) -> Self: ...
    def array_as(self, dtype: Dtype = ...) -> np.ndarray: ...
    def cast(self, value: int | float | np.ndarray) -> Any: ...
    def like(self, value: int | float, maxint: int | None = ...) -> Any: ...
    def copy(self, copy: bool = ...) -> Self: ...
    def to_int(self, intclass: Dtype = ...) -> np.ndarray: ...  # deprecated
    def to_float(self, floatclass: Dtype = ...) -> np.ndarray: ...  # deprecated

    # ---- spatial / plane access --------------------------------------
    def plane(self, planes: Any) -> Self: ...
    def contains(self, p: Array2d) -> bool | np.ndarray: ...
    def meshgrid(self) -> tuple[np.ndarray, np.ndarray]: ...
    def interp2d(self, *args: Any, **kwargs: Any) -> np.ndarray: ...

    # ---- colour ------------------------------------------------------
    def mono(self) -> Self: ...
    def red(self) -> Self: ...
    def green(self) -> Self: ...
    def blue(self) -> Self: ...
    def colorspace(self, dst: str, src: str | None = ...) -> Self: ...
    def invert(self) -> Self: ...

    # ---- border handling (defined in ImageSpatialMixin) --------------
    @staticmethod
    def _bordertype_cv(border: str, exclude: Any = None) -> int: ...
    @staticmethod
    def _bordertype_sp(border: str, exclude: Any = None) -> str: ...

    # ---- other image methods -----------------------------------------
    def smooth(self, *args: Any, **kwargs: Any) -> Self: ...
    def convolve(self, *args: Any, **kwargs: Any) -> Self: ...
    def trim(self, *args: Any, **kwargs: Any) -> Self: ...
    def colorize(self, *args: Any, **kwargs: Any) -> Self: ...
    def moments(self, binary: bool = ...) -> dict[str, float]: ...
    def disp(self, *args: Any, **kwargs: Any) -> Any: ...
    def paste(self, *args: Any, **kwargs: Any) -> None: ...

    @classmethod
    def Constant(cls, *args: Any, **kwargs: Any) -> Self: ...

    # ---- whole-image statistics -------------------------------------
    def min(self, *args: Any, **kwargs: Any) -> int | float: ...
    def max(self, *args: Any, **kwargs: Any) -> int | float: ...
    def __iter__(self) -> Any: ...

    # ---- arithmetic operators ----------------------------------------
    def __add__(self, other: Any) -> Self: ...
    def __radd__(self, other: Any) -> Self: ...
    def __iadd__(self, other: Any) -> Self: ...
    def __sub__(self, other: Any) -> Self: ...
    def __rsub__(self, other: Any) -> Self: ...
    def __isub__(self, other: Any) -> Self: ...
    def __mul__(self, other: Any) -> Self: ...
    def __rmul__(self, other: Any) -> Self: ...
    def __imul__(self, other: Any) -> Self: ...
    def __truediv__(self, other: Any) -> Self: ...
    def __rtruediv__(self, other: Any) -> Self: ...
    def __itruediv__(self, other: Any) -> Self: ...
    def __ifloordiv__(self, other: Any) -> Self: ...
    def __iand__(self, other: Any) -> Self: ...
    def __ior__(self, other: Any) -> Self: ...
    def __ixor__(self, other: Any) -> Self: ...
    def __ilshift__(self, other: Any) -> Self: ...
    def __irshift__(self, other: Any) -> Self: ...
